# Creates the Phase 29 bounded source manifest (phase29-freeze.json).
#
# The manifest records every included source file (path, byte size, SHA-256)
# plus the HEAD commit, toolchain and lockfile identities of the exact dirty
# working tree. It never modifies the tree and never includes secrets.
#
# Usage:
#   .\tools\make-source-manifest.ps1 -OutputPath .\phase29-freeze.json
param(
    [Parameter(Mandatory = $true)][string]$OutputPath,
    [string]$ReleaseVersion = "2.0.0",
    [string]$PublisherDisplayName = "GhitaBrowser"
)

$ErrorActionPreference = "Stop"

$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$excludedTopLevel = @(".git", "target", "dist", ".freebuff", ".zcode", "user_data", "cache", "downloads")
# Generated Phase 29 freeze outputs are not frozen build inputs.
$excludedFiles = @("phase29-freeze.json", "phase29-freeze.json.sha256.txt")

function Get-Sha256([string]$Path) {
    return (Get-FileHash -Algorithm SHA256 -Path $Path).Hash.ToLowerInvariant()
}

# Enumerate included source files (sorted, stable across runs).
$included = @()
Get-ChildItem -Path $root -Recurse -File -Force | ForEach-Object {
    $relative = $_.FullName.Substring($root.Length + 1).Replace("\", "/")
    $top = $relative.Split("/")[0]
    if ($excludedTopLevel -contains $top -or $excludedFiles -contains $relative) {
        return
    }
    $included += $relative
}
$included = $included | Sort-Object

$fileMap = [ordered]@{}
$totalBytes = 0
foreach ($relative in $included) {
    $path = Join-Path $root ($relative.Replace("/", "\"))
    $item = Get-Item -Path $path -Force
    $size = $item.Length
    $totalBytes += $size
    $fileMap[$relative] = [ordered]@{
        bytes  = $size
        sha256 = (Get-Sha256 $path)
    }
}

$head = (git -C $root rev-parse HEAD).Trim()
$headShort = $head.Substring(0, 7)
$branch = (git -C $root branch --show-current).Trim()
$porcelain = git -C $root status --porcelain
$dirtyCount = ($porcelain | Measure-Object).Count
$rustcVersion = (rustc --version).Trim()
$cargoVersion = (cargo --version).Trim()
$toolchainFile = (Get-Content (Join-Path $root "rust-toolchain.toml") -Raw).Trim()
$lockfilePath = Join-Path $root "Cargo.lock"
$lockfileBytes = (Get-Item -Path $lockfilePath).Length

$manifest = [ordered]@{
    manifest_version = 1
    created_at_unix  = [int64][DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
    release = [ordered]@{
        version       = $ReleaseVersion
        head_commit   = $head
        head_short    = $headShort
        branch        = $branch
        worktree_state = "dirty (uncommitted 2.0 work preserved)"
        dirty_file_count = $dirtyCount
    }
    toolchain = [ordered]@{
        rust_toolchain_file = $toolchainFile
        rustc_version       = $rustcVersion
        cargo_version       = $cargoVersion
    }
    lockfile = [ordered]@{
        path   = "Cargo.lock"
        bytes  = $lockfileBytes
        sha256 = (Get-Sha256 $lockfilePath)
    }
    source_files = $fileMap
    included_file_count = $included.Count
    total_source_bytes  = $totalBytes
    excluded_top_level_directories = $excludedTopLevel
    evidence_schema_version = 2
    matrix_version = 1
    supported_windows_targets = @(
        "windows-10-22h2-x64",
        "windows-11-23h2-x64",
        "windows-11-24h2-x64"
    )
    approved_signer = [ordered]@{
        publisher_display_name        = $PublisherDisplayName
        certificate_subject           = "<pending-user-approval>"
        certificate_thumbprint_sha256 = "<pending-user-approval>"
    }
    authorized_clean_vms = [ordered]@{
        "windows-10-22h2-x64" = "<pending-user-approval>"
        "windows-11-23h2-x64" = "<pending-user-approval>"
        "windows-11-24h2-x64" = "<pending-user-approval>"
    }
    reproducible_build_contract = [ordered]@{
        payload      = "reproducible_artifact_a and reproducible_artifact_b must be byte-identical unsigned builds produced from this frozen source manifest"
        distribution = "signed_artifact is the Authenticode-signed distribution envelope, verified by WinVerifyTrust plus the approved signer subject/thumbprint binding; envelope bytes may legitimately differ from the unsigned payload"
    }
    evidence_rules = [ordered]@{
        owner      = "release evidence is generated by authorized phase runners and reviewed by the user/reviewer; it never replaces a failed gate"
        timestamps = "every evidence artifact records completed_at_unix in UTC"
        hashes     = "every EvidenceArtifact records the SHA-256 of its current bytes"
        freshness  = "audit and external release evidence must be at most 24 hours old when Phase 34 runs"
        retention  = "evidence output root is dist/evidence/ (gitignored); candidates and reports are retained there"
        redaction  = "private keys, provider tokens, passwords and VM credentials never appear in evidence, reports, manifests or transcripts"
    }
    evidence_output_root = "dist/evidence/"
}

$json = $manifest | ConvertTo-Json -Depth 8
$outputFile = [IO.Path]::GetFullPath((Join-Path (Get-Location) $OutputPath))
$outputDir = [IO.Path]::GetDirectoryName($outputFile)
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}
Set-Content -Path $outputFile -Value $json -Encoding UTF8
$manifestHash = Get-Sha256 $outputFile
$checksumFile = "$outputFile.sha256.txt"
Set-Content -Path $checksumFile -Value "$manifestHash  $(Split-Path -Leaf $outputFile)" -Encoding ASCII

Write-Host "Wrote $outputFile"
Write-Host "Source files: $($included.Count), total bytes: $totalBytes"
Write-Host "Manifest SHA-256: $manifestHash"
Write-Host "Checksum: $checksumFile"
